export const metadata = {
  title: 'Module 1 / Step 1 - Ainslee + Rayna',
  description: 'Generated by RaynaUI',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
