export const metadata = {
  title: 'Dashboard - Ainslee + Rayna',
  description: 'Generated by RaynaUI',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
